# Generated by Django 3.0.5 on 2020-04-23 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0004_auto_20200422_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='voters',
            field=models.ManyToManyField(related_name='answer_voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
