# Generated by Django 3.0.5 on 2020-04-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented', models.IntegerField(default=0)),
                ('reputation', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('answers', models.IntegerField(default=0)),
                ('web_site', models.URLField(blank=True, default='')),
                ('github', models.URLField(blank=True, default='')),
                ('work_or_study', models.CharField(blank=True, default='', max_length=256)),
                ('position', models.CharField(blank=True, default='', max_length=256)),
                ('where', models.CharField(blank=True, default='', max_length=256)),
                ('about', models.TextField(blank=True, default='')),
                ('image', models.ImageField(default='default/profile_photo_default.jpg', upload_to='profile_pic')),
            ],
        ),
    ]
