# Generated by Django 3.0.5 on 2020-04-09 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='fav_question',
            field=models.ManyToManyField(blank=True, related_name='fav_question', to='questions.Question'),
        ),
        migrations.AddField(
            model_name='user_data',
            name='question',
            field=models.ManyToManyField(blank=True, to='questions.Question'),
        ),
        migrations.AddField(
            model_name='user_data',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
